### ISSUE TITLE
Todo list tracker.

### ISSUE THREAD

**Issue by StiliyanKushev** [AI-ASMR/asmr-gan-core#1]
Those are the main todos that will likely have to be done separately, in more or less that order.

- [x] Implement the training process and make a PR. ([ref](https://github.com/AI-ASMR/asmr-gan-core/tree/wip-model-architecture-and-training))
- [x] Create a flowchart explaining the model's structure in the README.md. ([ref](https://github.com/AI-ASMR/asmr-gan-core/tree/wip-model-architecture-and-training))
- [x] Implement the library and make a PR.
- [x] Setup Typedoc for both the library and the binary and update README.md.
- [ ] Implement unit tests for both the library and the internal functionality of the binary.
- [x] Create a docker container and Dockerfile for the binaries of the repository.  ([ref](https://github.com/AI-ASMR/asmr-gan-core/tree/docker-impl))

**Comment by StiliyanKushev** [comment]
Upon successful (manually confirmed) AI generated audio, the following should be done.

- [ ] Improve upon the library and model architecture (ACGAN instead of DCGAN) to enable classification and labeling of different triggers.
